---
# tasks file for install_nginx
    - name: Add epel-release repo
      yum:
        name: epel-release
        state: present
      become: true

    - name: Install nginx
      yum:
        name: nginx
        state: present
      become: true

    - name: create conf.d directory
      file:
        path: /etc/nginx/conf.d/
        state: directory
        mode: '0755'
      become: true

    - name: copy the nginx config file
      copy:
        src: "studentlist.conf"
        dest: /etc/nginx/conf.d/studentlist.conf
        mode: 755
      become: true
      notify: restart nginx

    - name: start nginx
      service:
          name: nginx
          state: started
      become: true